version: '3'

services:
  webapp:
    image: licenta:v1
    ports:
      - 8000:80
    restart: always
    depends_on:
      - database
  
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    volumes:
      - mydata:/var/opt/mssql/data
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd1
      - MSSQL_PID=Express
   volumes:
     mydata:/licenta/licenta/mydata

